"""Create rate limit configs table

Revision ID: 1f9793368bca
Revises: 6d5cb489f54b
Create Date: 2025-08-28 12:22:08.951350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f9793368bca'
down_revision: Union[str, Sequence[str], None] = '6d5cb489f54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corenest__rate_limit_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('requests_per_minute', sa.Integer(), nullable=True),
    sa.Column('requests_per_hour', sa.Integer(), nullable=True),
    sa.Column('requests_per_day', sa.Integer(), nullable=True),
    sa.Column('concurrent_requests_limit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['corenest__clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corenest__rate_limit_configs')
    # ### end Alembic commands ###
