"""remove auth_headers from api_logs

Revision ID: 24476ccffe41
Revises: 1f9793368bca
Create Date: 2025-08-29 01:09:12.220103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24476ccffe41'
down_revision: Union[str, Sequence[str], None] = '1f9793368bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corenest__api_logs', 'auth_headers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corenest__api_logs', sa.Column('auth_headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
