endpoints:
  completions:
    blocked_params:
      - model
      - provider
      - stream
      - stream_options
    defaults:
      model: null
      provider: null
      stream: false
      stream_options: null
  sentiments:
    blocked_params:
      - model
      - provider
      - temperature
      - tools
      - tool_choice
      - stream
      - stream_options
      - response_format
      - system_prompt
    defaults:
      model: null
      provider: null
      temperature: 0
      tools: null
      tool_choice: null
      stream: false
      stream_options: null
      response_format:
        type: json_object
  summaries:
    blocked_params:
      - model
      - provider
      - temperature
      - tools
      - tool_choice
      - stream
      - stream_options
      - response_format
      - system_prompt
    defaults:
      model: null
      provider: null
      temperature: 0
      tools: null
      tool_choice: null
      stream: false
      stream_options: null
      response_format: null
  embeddings:
    blocked_params:
      - model
    defaults:
      model: null
